-- Run this in Supabase → SQL Editor → New Query
ALTER TABLE public.scans
  ADD COLUMN IF NOT EXISTS platform                    text    DEFAULT 'twitter',
  ADD COLUMN IF NOT EXISTS username                    text    DEFAULT '',
  ADD COLUMN IF NOT EXISTS followers_count             int8    DEFAULT 0,
  ADD COLUMN IF NOT EXISTS following_count             int8    DEFAULT 0,
  ADD COLUMN IF NOT EXISTS follower_following_ratio    float8  DEFAULT 0,
  ADD COLUMN IF NOT EXISTS account_age_days            int4    DEFAULT 0,
  ADD COLUMN IF NOT EXISTS statuses_count              int4    DEFAULT 0,
  ADD COLUMN IF NOT EXISTS posts_per_day               float8  DEFAULT 0,
  ADD COLUMN IF NOT EXISTS content_density             float8  DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tweets_per_day              float8  DEFAULT 0,
  ADD COLUMN IF NOT EXISTS engagement_proxy            float8  DEFAULT 0,
  ADD COLUMN IF NOT EXISTS followers_log               float8  DEFAULT 0,
  ADD COLUMN IF NOT EXISTS following_log               float8  DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ratio_log                   float8  DEFAULT 0,
  ADD COLUMN IF NOT EXISTS activity_score              float8  DEFAULT 0,
  ADD COLUMN IF NOT EXISTS growth_signal               float8  DEFAULT 0,
  ADD COLUMN IF NOT EXISTS has_profile_image           int2    DEFAULT 0,
  ADD COLUMN IF NOT EXISTS verified                    int2    DEFAULT 0,
  ADD COLUMN IF NOT EXISTS bio_length                  int4    DEFAULT 0,
  ADD COLUMN IF NOT EXISTS username_randomness_score   float8  DEFAULT 0,
  ADD COLUMN IF NOT EXISTS username_length             int4    DEFAULT 0,
  ADD COLUMN IF NOT EXISTS prediction                  int4    DEFAULT 0,
  ADD COLUMN IF NOT EXISTS label                       text    DEFAULT '',
  ADD COLUMN IF NOT EXISTS fake_probability            float8  DEFAULT 0;
